spring:
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sf-service-application_db?createDatabaseIfNotExist=true
  profiles:
    active: development
