spring:
  application:
    name: sf-service-application
  jpa:
    properties:
      hibernate:
        column_ordering_strategy: legacy
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sf_service_application_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:0827}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}

server:
  port: 8081
  error:
    include-message: ALWAYS

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
