spring:
  application:
    name: sf-user-management-application
  profiles:
    active: development
server:
  error:
    include-message: always
  port: 8083
keycloak:
  serverUrl: https://auth.hexalyte.com/
  realm: service-finder-cloud
  clientId: sf-user-management-application
  clientSecret: KuGQBvfjpDgsl9tUkfsFW12MBEtvcMbE
  clientUuid: 6f1228a4-f19f-4286-8e03-adfa776a3aec
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true